### ISSUE TITLE
api/1.3/page/tv/children/front/{channel}

### ISSUE THREAD

**Issue by ukdtom** [drdk/mu-api#10]
Bare mig, eller spiller `http://www.dr.dk/mu-online/api/1.3/page/tv/children/front/dr1` ikke helt efter hensigten?

`http://www.dr.dk/mu-online/api/1.1/page/tv/children/front/dr1` spiller dog fint

mvh

Tommy

**Comment by ukdtom** [comment]
Så meget for licens pengene :(

**Comment by drdkthhj** [comment]
Hej Tommy @ukdtom.
Jeg fandt lige den her issue-tracker ved et tilfælde (kan se at den er senest vedligeholdt fra vores side i 2014).
Så inden jeg lukker den ned vil jeg da lige svare på din henvendelse vedr. endpointet /tv/children/front/{channel}
Dette endpoint anvedndes kun til børnekanalerne ultra og ramasjang, (hhv dr-ultra og dr-ramasjang som channel-slugs), og derfor virker det ikke for dr1 2 3 og k.

Med venlig hilsen
Thomas

**Comment by ukdtom** [comment]
Super, og takker

Og nysgerrig her....

Hvad skal man gøre for at få en API nøgle?

**Comment by drdkthhj** [comment]
Så lidt skam.
Jeg er ikke klar over hvad du mener med an api-nøgle?
drs mu-online api er som sådan offentligt tilgængeligt, du kan finde dokumentation her: [https://www.dr.dk/mu](https://www.dr.dk/mu) og her [https://www.dr.dk/mu-online/Help/1.4](https://www.dr.dk/mu-online/Help/1.4)
APIerne er fortrinsvis vedligeholdt i forhold til vores direkte samarbejdspartnere (app-udviklere til HBBtv, android, ios osv), så dokumentationen er ikke altid lige godt opdateret.
/Thomas

**Comment by ukdtom** [comment]
Jeg snakker on TV-Guide :)

http://api.yousee.tv/rest/tvguide

**Comment by drdkthhj** [comment]
Det er yousee du skal snakke med der, ikke os :)

**Comment by ukdtom** [comment]
Ups....og korrekt :-)
