### ISSUE TITLE
HELP: Get next release date for a show

### ISSUE THREAD

**Issue by istasi** [drdk/mu-api#11]
Unless im doing it completely wrong, is the only way to get the next release date to go though /api/1.4/schedule/ until you hit the show you want/need.

Is there no way to just go: urn:dr:mu:bundle:59b316dba11f9f236038b8d6 this show, when is the next episode?

**Comment by drdkthhj** [comment]
Hej istasi
Det er umiddelbart ikke muligt at anvende api-et til at modtage næste udsendelse. 
Værd i øvrigt opmærksom på, at selvom api og dokumentation er offentligt tilgængeligt, er det ikke tilladt at gengive materiale, dvs. udsendelser osv., uden eksplicit tilladelse fra DR. Dette er også angivet i bunden af alle sider på API-dokumentationen: "© Copyright DR. Materialet må ikke gengives uden tilladelse."
Du kan finde kontaktoplysninger til DR her www.dr.dk/kontakt , hvis du ønsker at forhøre dig om lov til at gengive materiale.
