### ISSUE TITLE
Exclude multiple ids?

### ISSUE THREAD

**Issue by waighei** [drdk/mu-api#7]
The [documentation] (http://www.dr.dk/mu-online/Help/1.3/Api/GET-api-1.3-list-id_limit_offset_excludeId) for URI parameter `excludeId` says the following:

>A list of ids to exclude from the list. These can be either urns or slugs (Optional)

It sounds like it should be possible to exclude multiple ids, but I have only been able to exclude one id:

`http://www.dr.dk/mu-online/api/1.3/list/taxa?limit=60&excludeid=taxa-1-56`

How can I also exclude e.g `taxa-2-56` and `taxa-3-56`?

**Comment by MrMads** [comment]
This was a mistake in the documentation. Unfortunately it's only possible to exclude one id through that method.

Sorry for the inconvenience.

Kind regards
Mads
