### ISSUE TITLE
OriginalTitle in ProgramCard

### ISSUE THREAD

**Issue by waighei** [drdk/mu-api#8]
MU API programcards contain `OriginalTitle` for non-Danish productions. This makes it possible to query e.g. IMDB for further information.

Would you consider to add `OriginalTitle` to MU-online API programcards?

**Comment by bobend** [comment]
Hello, 
MU-Online is designed to be as light-weight as possible and we do not add fields we don't need for our apps. 
Which client are you working on and do you an agreement with "DR Medier" to use the API? 
Cheers
Bo

**Comment by waighei** [comment]
Hello Bo,

> MU-Online is designed to be as light-weight as possible and we do not add fields we don't need for our apps.

Ok, thank you for the answer.

> Which client are you working on and do you an agreement with "DR Medier" to use the API?

I build a small DR TV app to learn more about app development. It will only be used by me.

I do not have an agreement with "DR Medier". I have read the [documentation](http://www.dr.dk/mu-online/Help/1.3/Docs/Intro) thoroughly, and did not find anything that said permission was required for using the API, so I just assumed that everyone was allowed to use it.

How can I get an agreement?

**Comment by bobend** [comment]
>I do not have an agreement with "DR Medier". I have read the documentation thoroughly, and did not find anything that said permission was required for using the API, so I just assumed that everyone was allowed to use it. 

In the bottom of every page it says `© Copyright DR. Materialet må ikke gengives uden tilladelse. `

You'll need to contact DR via www.dr.dk/kontakt they should be able to connect you with the proper department to get an angreement to use the api.
