### ISSUE TITLE
How to use GET-api-apiVersion-manifest-id?

### ISSUE THREAD

**Issue by mkjensen** [drdk/mu-api#9]
I don't understand how to use http://www.dr.dk/mu-online/Help/1.3/Api/GET-api-apiVersion-manifest-id.

Given a valid slug (e.g. "x-factor-2016-03-25") or a valid URN (e.g. "urn:dr:mu:programcard:56e9f9c0a11fa11ddc173d99"), then neither http://www.dr.dk/mu-online/api/1.3/manifest/x-factor-2016-03-25 nor http://www.dr.dk/mu-online/api/1.3/manifest/urn:dr:mu:programcard:56e9f9c0a11fa11ddc173d99 work.

However, the PrimaryAsset Uri (http://www.dr.dk/mu-online/api/1.3/bar/56f61e76a11f9f0db03ac95d) from the program card works.

What am I missing?

**Comment by MrMads** [comment]
1) The manifest controller only understands manifest urns as id. Not programcard slugs or urns. 

2) Which client are you working on and do you an agreement with "DR Medier" to use the API? 
In the bottom of every page it says © Copyright DR. Materialet må ikke gengives uden tilladelse.
You'll need to contact DR via www.dr.dk/kontakt they should be able to connect you with the proper department to get an agreement to use the api.

**Comment by mkjensen** [comment]
1) I see. Do you have an example on how to use it? Where do you get manifest urns?

2) I'm currently having fun building an Android TV app. It's actually getting quite okay so I'm considering if it should be included in Google Play Store. I'll use the contact form and see what happens.

**Comment by bobend** [comment]
The manifest controller must not be called directly. Should only be redirected to from the `bar`-controller.

**Comment by mkjensen** [comment]
I see. Didn't get that from the description at http://www.dr.dk/mu-online/Help/1.3/Api/GET-api-apiVersion-manifest-id. Thanks.
